#!/usr/bin/env bash
# displays "To infinity and beyond" indefinitely
# displays "I am invincible" upon receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM
f=1
while [ $f -eq 1 ]; do
	echo "To infinity and beyond"
	sleep 2
done
