#!/usr/bin/env bash
# loops 10 times, displaying "bad luck" on the 4th iteration and
# "good luck" on the 8th while "Best School" on every other

i=1
while [ $i -le 10 ]; do
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
