#!/usr/bin/env bash
# This script gives information about the "school" file.
# If the file exists, it prints: "school file exists"
# If it does not exist, it prints: "school file does not exit"
# If it exists and is empty it prints: "school file is empty"
# Otherwise, it prints: "school file is not empty"
# If if exists and is a regular file, it prints: "school is a regular file"
# Otherwise, it prints nothing

f="school"
if [ -e "$f" ]; then
	echo "school file exists"
	if [ -s "$f" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$f" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
