#!/usr/bin/env bash
# resolves 127.0.0.1 to 127.0.0.2 and facebook to 8.8.8.8

cp /etc/hosts ~/hosts
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts
cp -f ~/hosts /etc/hosts
rm ~/hosts
